apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-interview-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-interview-demo
  template:
    metadata:
      labels:
        app: k8s-interview-demo
    spec:
      containers:
        - name: app
          image: k8s-interview-demo:v4
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: k8s-interview-demo-config
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-interview-demo-secret
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10