apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-project
spec:
  ingressClassName: traefik
  rules:
    - host: k8s-project.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-project
                port:
                  number: 80